services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minio_net
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DEFAULT_BUCKETS=documents

networks:
    minio_net:
      driver: bridge

volumes:
    minio_data:
      driver: local